### ISSUE TITLE
extra step in getting User instance on server

### ISSUE THREAD

**Issue by Mollie-S** [42-jkoers/ft_transcendence#140]
a funny discovery:
```
const userId = client.data.user.id;
const user = await this.userService.findByID(userId);
```
returns the same User instance as
```
const user = client.data.user
```

Not urgent, just ugly and requires an additional query to db. 
Probably we can clean up while implementing other stuff in our services
?

**Comment by aprilmayjune135** [comment]
The user instance of `client.data.user` is decided at the `handConnection()` when socket is connected.
Later on, the user might change it's username/avatar/2F and etc, so this client.data.user will be outdated.

In my opinion, in most cases, it's always safer to use just `user id` and retrieve the latest information from the database, as user id is the only constant that will never change.
(specially for friends relationship, states are changing at any time for any user. you never know whether your current user instance is the latest one)

That said, i would even suggest for the `client.data.user`, instead of saving the user instance, we could save only the user id. Let me know how you think.

**Comment by ergunirem** [comment]
I agree with Aileen. This was due to the fact that user is only saved on connection but username might change without disconnecting. So, it's always best to retrieve the user info from the database. On the last note, indeed we can just save the userId. If we decide to change this I can adjust it with a separate PR and close the issue. Let me know.

**Comment by Mollie-S** [comment]
@SirMorfield comments explain the reason for retrieving a user instance from id

**Comment by Mollie-S** [comment]
closing it
